update

diff --git a/.github/workflows/immortalwrt-r66s-6.yml b/.github/workflows/immortalwrt-r66s-6.yml
--- a/.github/workflows/immortalwrt-r66s-6.yml
+++ b/.github/workflows/immortalwrt-r66s-6.yml
@@ -31,13 +31,16 @@
 
 
   env:
+    FREE_DISK_SH: scripts/free_disk_space.sh
+    ENV_SH: scripts/environment.sh
     REPO_URL: https://github.com/immortalwrt/immortalwrt
     REPO_BRANCH: openwrt-24.10
-    FEEDS_CONF: feeds.conf.default
-    CONFIG_FILE: r66s/6.1/config/imm-FastRhino-r66s-6.1.info
-    DIY_P1_SH: r66s/6.1/r66s-test-1.sh
-    DIY_P2_SH: r66s/6.1/r66s-my-2.sh
-    Firmware_Name: imm-FastRhino-r66s-6.1 
+    PLATFORM_FILE: configs/rockchip.txt
+    CONFIG_FILE: configs/Packages.txt
+    SETTINGS_SH: scripts/init-settings.sh
+    PACKAGES_SH: scripts/packages.sh
+    CLASH_CORE_SH: scripts/preset-clash-core-arm64-L.sh
+    Firmware_Name: imm-FastRhino-r66s
     UPLOAD_BIN_DIR: false
     UPLOAD_FIRMWARE: true
     UPLOAD_BUILDINFO: true
@@ -47,59 +50,34 @@
     UPLOAD_RELEASE: false
     GITHUB_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
     TZ: Asia/Shanghai  
-    KERNEL_VERSION: 6.1.79
+
 
   jobs:
     build:
-      runs-on: Ubuntu-22.04
+      runs-on: Ubuntu-24.04
 
       steps:
+      - name: 检查
+        uses: actions/checkout@main
 
-      - name: 释放磁盘空间
-        uses: endersonmenezes/free-disk-space@v2
-        with:
-          remove_android: true
-          remove_dotnet: true
-          remove_haskell: true
-          remove_tool_cache: true
-          remove_swap: true
-          remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-*"
-          remove_packages_one_command: true
-          remove_folders: "/usr/share/swift /usr/share/miniconda /usr/share/az* /usr/share/glade* /usr/local/lib/node_modules /usr/local/share/chromium /usr/local/share/powershell"
-          testing: false
-      
-      - name: CPU检测
-        run: |
-          echo "警告⚠"
-          echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
-          echo -e "已知CPU型号(降序): 7763，8370C，8272CL，8171M，E5-2673\n"
-          echo "--------------------------CPU信息--------------------------"
-          echo "CPU物理数量: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
-          echo "CPU核心数量: $(nproc)"
-          echo -e "CPU型号信息:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
-          echo "--------------------------内存信息--------------------------"
-          echo "已安装内存详细信息:"
-          echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
-          echo "--------------------------硬盘信息--------------------------"
-          echo "硬盘数量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT
-
-
-        
-
-      - name: 初始化系统环境
+      - name: 初始化环境
         env:
           DEBIAN_FRONTEND: noninteractive
         run: |
+          chmod +x $FREE_DISK_SH && $FREE_DISK_SH
+          sudo -E apt-get -qq update -y
+          sudo -E apt-get -qq full-upgrade -y
+          chmod +x $ENV_SH && $ENV_SH
           sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
-          sudo -E apt-get -qq update
-          sudo -E apt-get -qq install $(curl -fsSL https://github.com/popeyema/OpenWrt-R66s/raw/main/depends-ubuntu-latest)
-          sudo apt install clang
-          sudo -E apt -y install rename
-          sudo -E apt-get -qq autoremove --purge
-          sudo -E apt-get -qq clean
           sudo timedatectl set-timezone "$TZ"
+          docker image prune -a -f
+          docker container prune -f
           sudo mkdir -p /workdir
           sudo chown $USER:$GROUPS /workdir
+
+      - name: 检查空间使用情况1
+        if: (!cancelled())
+        run: df -hT
 
 
       - name: 更新时区、编译时间
@@ -113,48 +91,135 @@
           START_TIME=`date +'%Y-%m-%d %H:%M:%S'`
           echo "START_SECONDS=$(date --date="$START_TIME" +%s)" >> $GITHUB_ENV
 
-      - name: 准备完成
-        uses: actions/checkout@v4
-
-      - name: 下载源代码
+      - name: 克隆源码
         working-directory: /workdir
         run: |
-          df -hT $PWD
-          git clone $REPO_URL -b $REPO_BRANCH openwrt
+          git clone $REPO_URL --depth 1 -b $REPO_BRANCH openwrt
           ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
 
-      - name: 缓存
+      - name: 设置 VERSION 环境变量
+        run: echo "VERSION=${REPO_BRANCH#*-}" >> $GITHUB_ENV
+
+      - name: 开启缓存
         uses: klever1988/cachewrtbuild@main
-        if: env.CACHE_BUILD == 'true' || (github.event.inputs.CACHE_BUILD == 'true')
         with:
           ccache: 'true'
-          clean: 'false'
-          mixkey: '${{ env.Firmware_Name }}-${{ env.START_SECONDS }}'
+          mixkey: '${{ env.VERSION }}-rockchip'
           prefix: ${{ github.workspace }}/openwrt
 
 
       
-      - name: 更新源 #Update feeds
-        run: cd openwrt && ./scripts/feeds update -a
-
-      - name: 安装源 #Install feeds
-        run: cd openwrt && ./scripts/feeds install -a
-
-      - name: patch1补丁和自定义设置
+      - name: 安装 feeds
         run: |
-          [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
-          chmod +x $DIY_P1_SH
           cd openwrt
-          $GITHUB_WORKSPACE/$DIY_P1_SH
+          ./scripts/feeds update -a
+          ./scripts/feeds install -a
 
-          
-      - name: patch2补丁和自定义设置
+      - name: 导入补丁和配置 & 执行脚本
         run: |
-          [ -e files ] && mv files openwrt/files
-          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
-          chmod +x $DIY_P2_SH
+          [ -d files ] && mv files openwrt/files || echo "files not found"
+          [ -f $PLATFORM_FILE ] && cat $PLATFORM_FILE >> openwrt/.config
+          [ -f $CONFIG_FILE ] && cat $CONFIG_FILE >> openwrt/.config
           cd openwrt
-          $GITHUB_WORKSPACE/$DIY_P2_SH
+          chmod +x $GITHUB_WORKSPACE/$SETTINGS_SH && $GITHUB_WORKSPACE/$SETTINGS_SH
+          chmod +x $GITHUB_WORKSPACE/$PACKAGES_SH && $GITHUB_WORKSPACE/$PACKAGES_SH
+          chmod +x $GITHUB_WORKSPACE/$CLASH_CORE_SH && $GITHUB_WORKSPACE/$CLASH_CORE_SH
+
+      - name: 下载文件
+        run: |
+          cd openwrt
+          make defconfig
+          make download -j8 V=10
+          find dl -size -1024c -exec ls -l {} \;
+          find dl -size -1024c -exec rm -f {} \;
+
+      - name: 空间使用情况2
+        if: (!cancelled())
+        run: df -hT
+
+      - name: 编译工具链
+        id: mtools
+        run: |
+          cd openwrt
+          make defconfig
+          echo -e "$(($(nproc)+1)) thread compile"
+          make tools/compile -j$(($(nproc)+1)) || make tools/compile -j1 V=s
+          make toolchain/compile -j$(($(nproc)+1)) || make toolchain/compile -j1 V=s
+          echo "status=success" >> $GITHUB_OUTPUT
+
+      - name: 空间使用情况3_1
+        if: (!cancelled())
+        run: df -hT
+
+      - name: 清除工具链编译中间产物...
+        if: steps.mtools.outputs.status == 'success' && !cancelled()
+        run: |
+          cd openwrt
+          rm -rf dl/*
+          rm -rf build_dir/host/*
+          rm -rf build_dir/toolchain-*
+
+      - name: 空间使用情况3_2
+        if: (!cancelled())
+        run: df -hT
+
+      - name: 编译内核
+        id: mkernel
+        if: steps.mtools.outputs.status == 'success' && !cancelled()
+        run: |
+          cd openwrt
+          echo -e "$(($(nproc)+1)) thread compile"
+          make target/linux/compile -j$(($(nproc)+1)) || make target/linux/compile -j1 V=s
+          echo "status=success" >> $GITHUB_OUTPUT
+
+      - name: 空间使用情况4
+        if: (!cancelled())
+        run: df -hT
+
+      - name: 编译插件
+        id: mpackage
+        if: steps.mkernel.outputs.status == 'success' && !cancelled()
+        run: |
+          cd openwrt
+          echo -e "$(($(nproc)+1)) thread compile"
+          make package/compile -j$(($(nproc)+1)) || make package/compile -j1 V=s
+          make package/index
+          make package/install -j$(nproc) || make package/install -j1 V=s
+          echo "status=success" >> $GITHUB_OUTPUT
+
+      - name: 空间使用情况5
+        if: (!cancelled())
+        run: df -hT
+
+      - name: 清除插件编译文件
+        id: cpackage
+        if: steps.mpackage.outputs.status == 'success' && !cancelled()
+        run: |
+          cd openwrt
+          rm -rf build_dir/target-*/host
+          echo "status=success" >> $GITHUB_OUTPUT
+
+      - name: 空间使用情况6
+        if: (!cancelled())
+        run: df -hT
+
+      - name: 编译固件
+        id: compile
+        if: steps.cpackage.outputs.status == 'success' && !cancelled()
+        run: |
+          cd openwrt
+          echo -e "$(($(nproc)+1)) thread compile"
+          make target/install -j$(nproc) || make target/install -j1 V=s
+          make json_overview_image_info
+          make checksum
+          echo "status=success" >> $GITHUB_OUTPUT
+          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
+          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
+          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
+
+      - name: 空间使用情况7
+        if: (!cancelled())
+        run: df -hT
 
       - name: SSH connection to Actions
         uses: P3TERX/ssh2actions@v1.0.0
@@ -162,96 +227,30 @@
         env:
           TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
           TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
-          
-      - name: 输出编译信息
-        run: |
-          cd openwrt
-          echo " 系统空间      类型   总数  已用  可用 使用率"
-          df -hT $PWD
-          
-          echo
-          echo "=========================================="
-          echo
 
-          ZZZ="package/lean/default-settings/files/zzz-default-settings"
-          echo "DISTRIB_REVISION=$(cat $ZZZ|grep DISTRIB_REVISION= | sed 's/^.\{24\}//g' | sed 's/.\{26\}$//')" >> $GITHUB_ENV
-          echo "KERNEL_PATCHVER=$(cat target/linux/rockchip/Makefile|grep KERNEL_PATCHVER | sed 's/^.\{17\}//g')" >> $GITHUB_ENV
-          echo "	    当前编译版本：$(cat $ZZZ|grep DISTRIB_REVISION= | sed 's/^.\{24\}//g' | sed 's/.\{26\}$//')"
-          echo "	    内核版本：$(cat target/linux/rockchip/Makefile|grep KERNEL_PATCHVER | sed 's/^.\{17\}//g')"
-
-          echo
-          echo "=========================================="
-
-          grep -i CONFIG_PACKAGE_luci-app .config | grep  -v \# > Plug-in
-          grep -i CONFIG_PACKAGE_luci-theme .config | grep  -v \# >> Plug-in
-          sed -i '/INCLUDE/d' Plug-in > /dev/null 2>&1
-          sed -i 's/CONFIG_PACKAGE_/、/g' Plug-in
-          sed -i '/Transparent_Proxy/d' Plug-in > /dev/null 2>&1 #排除 luci-app-passwall_Transparent_Proxy
-          sed -i '/qbittorrent-simple_dynamic/d' Plug-in > /dev/null 2>&1 #排除 luci-app-qbittorrent-simple_dynamic
-          sed -i 's/=y/\ /g' Plug-in
-          awk '$0=NR$0' Plug-in > Plug-2
-          awk '{print "	" $0}' Plug-2 > Plug-in
-
-          echo
-          echo
-          echo "	      已选插件列表"
-          cat Plug-in
-          rm -rf {Plug-in,Plug-2}
-
-          echo
-          echo "=========================================="
-
-          echo
-          echo
-          echo "输出完整插件信息..."
-          echo
-          echo
-          cat .config
-
-      - name: 下载固件包
-        id: package
-        run: |
-          cd openwrt
-          make defconfig
-          make download -j8
-          find dl -size -1024c -exec ls -l {} \;
-          find dl -size -1024c -exec rm -f {} \;
-
-      - name: 开始编译固件
-        id: compile
-        run: |
-          cd openwrt
-          echo -e "$(nproc) thread compile"
-          make -j$(nproc) || make -j1 || make -j1 V=s
-          echo "status=success" >> $GITHUB_OUTPUT
-          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
-          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
-          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
-          
-      - name: 检查空间使用情况
-        run: |
-          echo "=========================================="
-          echo "----------------空间使用-------------------"
-          echo "=========================================="
-          echo " 系统空间      类型   总数  已用  可用 使用率"
-          df -hT
-          echo "=========================================="
-          du -h --max-depth=1 openwrt/ --exclude=build_dir --exclude=bin
-          du -h --max-depth=1 openwrt/build_dir
-          du -h --max-depth=1 openwrt/bin
+      - name: 上传 bin 目录
+        uses: actions/upload-artifact@main
+        if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
+        with:
+          name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
+          path: openwrt/bin
 
       - name: 整理文件
         id: organize
-        if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
+        if: steps.compile.outputs.status == 'success' && !cancelled()
         run: |
           cd openwrt/bin/targets/*/*
+          rm -rf *.bin
+          rm -rf *.buildinfo 
+          rm -rf *.json 
+          rm -rf *.manifest 
           rm -rf packages
           echo "FIRMWARE=$PWD" >> $GITHUB_ENV
           echo "status=success" >> $GITHUB_OUTPUT
 
       - name: 上传固件目录
         uses: actions/upload-artifact@main
-        if: steps.organize.outputs.status == 'success' && !cancelled()
+        if: env.UPLOAD_FIRMWARE == 'true' && steps.organize.outputs.status == 'success' && !cancelled()
         with:
           name: ${{ env.Firmware_Name }}_${{ env.REPO_BRANCH }}_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
           path: ${{ env.FIRMWARE }}
@@ -282,7 +281,7 @@
 
       - name: 生成发布标签
         id: tag
-        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
+        if: env.UPLOAD_RELEASE == 'true' && steps.compile.outputs.status == 'success' && !cancelled()
         run: |
           echo "release_tag=$(date +"%Y.%m.%d")-Lean" >> $GITHUB_OUTPUT
           echo "release_date=$(date +"%Y.%m.%d")" >> $GITHUB_OUTPUT
@@ -316,19 +315,27 @@
           body_path: release.txt
           files: ${{ env.FIRMWARE }}/*
 
-      - name: 删除运行记录
-        uses: Mattraks/delete-workflow-runs@main
-        continue-on-error: true
-        with:
-          retain_days: 3     #保留最后多少记录不删除
-          keep_minimum_runs: 0
+      # - name: 删除运行记录
+      #   uses: Mattraks/delete-workflow-runs@main
+      #   continue-on-error: true
+      #   with:
+      #     retain_days: 3     #保留最后多少记录不删除
+      #     keep_minimum_runs: 0
 
       - name: 删除自动发布的旧固件
         uses: dev-drprasad/delete-older-releases@master
-        continue-on-error: true
-        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
+        #   continue-on-error: true
+        if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
         with:
           keep_latest: 20        #保留多少个releases不删除
           delete_tags: true
         env:
           GITHUB_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
+
+      - name: 删除以前的工作流程
+        uses: Mattraks/delete-workflow-runs@v2
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          repository: ${{ github.repository }}
+          retain_days: 3
+          keep_minimum_runs: 3
