Update JBT-Lean-text.yml

diff --git a/.github/workflows/JBT-Lean-text.yml b/.github/workflows/JBT-Lean-text.yml
--- a/.github/workflows/JBT-Lean-text.yml
+++ b/.github/workflows/JBT-Lean-text.yml
@@ -35,14 +35,17 @@ on:
 
     
 env:
+  GITHUB_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
   FREE_DISK_SH: scripts/free_disk_space.sh
   ENV_SH: scripts/environment.sh
   REPO_URL: https://github.com/coolsnowwolf/lede
   REPO_BRANCH: master
-  Firmware_Name: JBT-Lean
+  Firmware_Name: JBT-Lean-text
   CONFIG_FILE: config/Lean.txt
+  CONFIG_5G: configs/Packages-5G.txt
   SETTINGS_SH: scripts/JBT-init-settings.sh
   PACKAGES_SH: smpackage/Jbt-Lean-packages.sh
+  INSTALL5G_SH: scripts/install-5G.sh
   CLASH_CORE_SH: scripts/preset-clash-core-amd64.sh
   UPLOAD_BIN_DIR: false
   UPLOAD_FIRMWARE: true
@@ -51,8 +54,7 @@ env:
   UPLOAD_COWTRANSFER: false
   UPLOAD_WETRANSFER: false
   UPLOAD_RELEASE: true
-  GITHUB_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
-  TZ: Asia/Shanghai  
+    TZ: Asia/Shanghai  
 
 jobs:
 
@@ -67,20 +69,31 @@ jobs:
       - name: 检查
         uses: actions/checkout@main
 
+      - name: 检测 /dev/sda1 分区是否存在（Overlay部分）
+        id: overlay
+        run: |
+          if [ ! -b /dev/sda1 ]; then
+            echo "错误：/dev/sda1 分区不存在，无法继续执行 OverlayFS 相关操作，退出 Actions！"
+            exit 1  # 退出并标记 Actions 执行失败
+          fi
+            echo "成功检测到 /dev/sda1 分区，继续执行后续步骤。"
+
       - name: 初始化环境
         env:
           DEBIAN_FRONTEND: noninteractive
         run: |
           chmod +x $FREE_DISK_SH && $FREE_DISK_SH
+          sudo -E apt-get -qq update -y
+          sudo -E apt-get -qq full-upgrade -y
           chmod +x $ENV_SH && $ENV_SH
-          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
+          sudo rm -rf /etc/apt/sources.list.d/*
+          sudo rm -rf /var/lib/apt/lists/*
+          # 设置时区
           sudo timedatectl set-timezone "$TZ"
-          docker image prune -a -f
-          docker container prune -f
           sudo mkdir -p /workdir
           sudo chown $USER:$GROUPS /workdir
 
-      - name: 检查空间使用情况1
+      - name: 检查空间使用情况
         if: (!cancelled())
         run: df -hT
 
@@ -97,23 +110,79 @@ jobs:
           START_TIME=`date +'%Y-%m-%d %H:%M:%S'`
           echo "START_SECONDS=$(date --date="$START_TIME" +%s)" >> $GITHUB_ENV
 
-      - name: 下载源代码
+      - name: 创建 OverlayFS 目录结构（Overlay部分）
+        run: |
+          sudo mkdir -p /overlay/lower
+          sudo mkdir -p /mnt/overlay/upper
+          sudo mkdir -p /mnt/overlay/work
+          # 下面1行去除Overlay需要还原到 初始化环境中
+          sudo mkdir -p /workdir
+          sudo chmod 777 /overlay/lower
+          sudo chmod 777 /mnt/overlay/upper
+
+      - name: 挂载 OverlayFS 合并分区（Overlay部分）
+        run: |
+          sudo mount -t overlay overlay \
+          -o rw,lowerdir=/overlay/lower,upperdir=/mnt/overlay/upper,workdir=/mnt/overlay/work /workdir
+          mount | grep overlay
+
+      - name: 设置 /workdir 权限（Overlay部分）
+        run: |
+          # 下面1行去除Overlay需要还原到 初始化环境中
+          sudo chown $USER:$GROUPS /workdir
+
+      - name: 检查空间使用情况（OverlayFS是否生效）
+        if: (!cancelled())
+        run: df -hT
+
+      - name: 克隆源码
         working-directory: /workdir
         run: |
           git clone $REPO_URL --depth 1 -b $REPO_BRANCH openwrt
           ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
 
+          cd ./openwrt/ && echo "WRT_HASH=$(git log -1 --pretty=format:'%h')" >> $GITHUB_ENV
 
-      - name: 设置 VERSION 环境变量
-        run: echo "VERSION=${REPO_BRANCH#*-}" >> $GITHUB_ENV
-
-      - name: 缓存
-        uses: klever1988/cachewrtbuild@main
-        if: env.CACHE_BUILD == 'true' || (github.event.inputs.CACHE_BUILD == 'true')
+      - name: 检查缓存
+        id: check-cache
+        uses: actions/cache@main
         with:
-          ccache: 'true'
-          mixkey: '${{ env.VERSION }}_${{ env.Firmware_Name }}'
-          prefix: ${{ github.workspace }}/openwrt
+          key: x86-${{env.REPO_BRANCH}}-${{env.WRT_HASH}}
+          restore-keys: x86-${{env.REPO_BRANCH}}
+          path: |
+            ./openwrt/.ccache
+            ./openwrt/staging_dir/host*
+            ./openwrt/staging_dir/tool*
+
+      - name: 开启CCACHE配置
+        run: |
+          echo 'CONFIG_DEVEL=y' >> openwrt/.config
+          echo 'CONFIG_CCACHE=y' >> openwrt/.config       
+          
+      - name: 更新缓存
+        run: |
+          if [ -d "./openwrt/staging_dir" ]; then
+            find "./openwrt/staging_dir" -type d -name "stamp" -not -path "*target*" | while read -r DIR; do
+              find "$DIR" -type f -exec touch {} +
+            done
+
+            mkdir -p ./openwrt/tmp && echo "1" > ./openwrt/tmp/.build
+
+            echo "toolchain skiped done!"
+          else
+            echo "caches missed!"
+          fi
+
+          if ${{steps.check-cache.outputs.cache-hit != 'true'}}; then
+            CACHE_LIST=$(gh cache list --key "x86-$REPO_BRANCH" | cut -f 1)
+            for CACHE_KEY in $CACHE_LIST; do
+              gh cache delete $CACHE_KEY
+            done
+  
+            echo "caches cleanup done!"
+          fi
+
+
 
       - name: 安装 feeds
         run: |
@@ -123,12 +192,16 @@ jobs:
 
       - name: 导入补丁和配置 & 执行脚本
         run: |
-            [ -d files ] && mv files openwrt/files || echo "files not found"
-            [ -f $CONFIG_FILE ] && cat $CONFIG_FILE >> openwrt/.config
-            cd openwrt
-            chmod +x $GITHUB_WORKSPACE/$SETTINGS_SH && $GITHUB_WORKSPACE/$SETTINGS_SH
-            chmod +x $GITHUB_WORKSPACE/$PACKAGES_SH && $GITHUB_WORKSPACE/$PACKAGES_SH
-            chmod +x $GITHUB_WORKSPACE/$CLASH_CORE_SH && $GITHUB_WORKSPACE/$CLASH_CORE_SH          
+          [ -d files ] && mv files openwrt/files || echo "files not found"
+          [ -f $PLATFORM_FILE ] && cat $PLATFORM_FILE >> openwrt/.config
+          [ -f $CONFIG_FILE ] && cat $CONFIG_FILE >> openwrt/.config
+          [ -f $CONFIG_5G ] && cat $CONFIG_5G >> openwrt/.config
+          cd openwrt
+          chmod +x $GITHUB_WORKSPACE/$SETTINGS_SH && $GITHUB_WORKSPACE/$SETTINGS_SH
+          chmod +x $GITHUB_WORKSPACE/$PACKAGES_SH && $GITHUB_WORKSPACE/$PACKAGES_SH
+         chmod +x $GITHUB_WORKSPACE/$INSTALL5G_SH && $GITHUB_WORKSPACE/$INSTALL5G_SH
+         chmod +x $GITHUB_WORKSPACE/$CLASH_CORE_SH && $GITHUB_WORKSPACE/$CLASH_CORE_SH
+   
 
       - name: SSH connection to Actions
         uses: P3TERX/ssh2actions@v1.0.0
@@ -152,100 +225,28 @@ jobs:
         run: df -hT
 
       - name: 编译工具链
-        id: mtools
-        run: |
-            cd openwrt
-            make defconfig
-            echo -e "$(($(nproc)+1)) thread compile"
-            make tools/compile -j$(($(nproc)+1)) || make tools/compile -j1 V=s
-            make toolchain/compile -j$(($(nproc)+1)) || make toolchain/compile -j1 V=s
-            echo "status=success" >> $GITHUB_OUTPUT
-
-      - name: 空间使用情况3_1
-        if: (!cancelled())
-        run: df -hT
-
-      - name: 清除工具链编译中间产物...
-        if: steps.mtools.outputs.status == 'success' && !cancelled()
-        run: |
-            cd openwrt
-            rm -rf dl/*
-            rm -rf build_dir/host/*
-            rm -rf build_dir/toolchain-*
-
-      - name: 空间使用情况3_2
-        if: (!cancelled())
-        run: df -hT
-
-      - name: 编译内核
-        id: mkernel
-        if: steps.mtools.outputs.status == 'success' && !cancelled()
+        id: compile
         run: |
           cd openwrt
-          echo -e "$(($(nproc)+1)) thread compile"
-          make target/linux/compile -j$(($(nproc)+1)) || make target/linux/compile -j1 V=s
+          echo -e "$(nproc) thread compile"
+          make -j$(nproc) || make -j1 || make -j1 V=s
+          echo "======================="
+          echo "Space usage:"
+          echo "======================="
+          df -h
+          echo "======================="
+          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
+          du -h --max-depth=1 ./build_dir
+          du -h --max-depth=1 ./bin
           echo "status=success" >> $GITHUB_OUTPUT
           grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
           [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
           echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
 
-
-      - name: 空间使用情况4
-        if: (!cancelled())
-        run: df -hT
-        
-      - name: 编译插件
-        id: mpackage
-        if: steps.mkernel.outputs.status == 'success' && !cancelled()
-        run: |
-          cd openwrt
-          echo -e "$(($(nproc)+1)) thread compile"
-          make package/compile -j$(($(nproc)+1)) || make package/compile -j1 V=s
-          make package/install -j$(nproc) || make package/install -j1 V=s
-          make package/index
-          echo "status=success" >> $GITHUB_OUTPUT
-          
-      - name: 空间使用情况5
+      - name: 空间使用情况（编译占用）
         if: (!cancelled())
         run: df -hT
 
-      - name: 清除插件编译文件
-        id: cpackage
-        if: steps.mpackage.outputs.status == 'success' && !cancelled()
-        run: |
-            cd openwrt
-            rm -rf build_dir/target-*/host
-            echo "status=success" >> $GITHUB_OUTPUT
-
-      - name: 空间使用情况6
-        if: (!cancelled())
-        run: df -hT
-
-      - name: 编译固件
-        id: compile
-        if: steps.cpackage.outputs.status == 'success' && !cancelled()
-        run: |
-            cd openwrt
-            echo -e "$(($(nproc)+1)) thread compile"
-            make target/install -j$(nproc) || make target/install -j1 V=s
-            make json_overview_image_info
-            make checksum
-            echo "status=success" >> $GITHUB_OUTPUT
-
-      - name: 空间使用情况7
-        if: (!cancelled())
-        run: df -hT
-
-      # - name: 检查空间使用情况
-      #   if: steps.compile.outputs.status == 'success' && !cancelled()
-      #   run: df -hT
-
-      # - name: SSH connection to Actions
-      #   uses: P3TERX/ssh2actions@v1.0.0
-      #   if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
-      #   env:
-      #     TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
-      #     TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}  
 
       - name: 整理文件
         id: organize
